server:
  port: 12316
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/linktree
    password: ${LINKNEST_DB_PASSWORD}
    username: ${LINKNEST_DB_USERNAME}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  security:
    sign-key: ${LINKNEST_SIGNING_KEY}
  main:
    allow-bean-definition-overriding: true
linknest:
  max-count: 5
